import { Match } from "../types/Match";
import fazeLight from "@/assets/logos/Atlanta_FaZe_Light.png";
import fazeDark from "@/assets/logos/Atlanta_FaZe_Dark.png";
import thieves from "@/assets/logos/LA-Thieves.png";
import legion from "@/assets/logos/Vegas_Legion.png";
import opticLight from "@/assets/logos/OpTic_Texas_Light.png";
import opticDark from "@/assets/logos/OpTic_Texas_Dark.png";
import surge from "@/assets/logos/Seattle_Surge.png";

export const MATCH_DATA: Match[] = [
    {
        id: 1,
        majorId: 1,
        team1: {
            id: 1,
            name: "Atlanta FaZe",
            location: "United States",
            created: new Date("2019-05-02T04:00:00.000+00:00"),
            affiliated: "FaZe Clan",
            coach: 'James "Crowder" Replays',
            owner: "Atlanta Esports Ventures",
            points: 50,
            ticker: "TEST",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team2: {
            id: 6,
            name: "Los Angeles Thieves",
            location: "United States",
            created: new Date("2020-11-06T05:00:00.000+00:00"),
            affiliated: "100 Thieves",
            coach: 'Jordan "JKap" Kaplan',
            owner: "N/A",
            points: 30,
            ticker: "TEST",
            logoDark: thieves,
            logoLight: thieves,
        },
        team1Score: 3,
        team2Score: 1,
        round: "Qualifiers",
        date: new Date("2023-12-06T00:00:00.000+00:00"),
    },
    {
        id: 2,
        majorId: 1,
        team1: {
            id: 4,
            name: "Las Vegas Legion",
            location: "United States",
            created: new Date("2022-09-12T04:00:00.000+00:00"),
            affiliated: "N/A",
            coach: 'Dylan "Theory" McGee',
            owner: "c0ntact Gaming, LLC",
            points: 10,
            ticker: "TEST",
            logoDark: legion,
            logoLight: legion,
        },
        team2: {
            id: 1,
            name: "OpTic Texas",
            location: "United States",
            created: new Date("2021-11-08T05:00:00.000+00:00"),
            affiliated: "Team Envy",
            coach: 'Raymond "Rambo" Lussier',
            owner: "Hector Rodriguez & Mike Rufail",
            points: 60,
            ticker: "TEST",
            logoDark: opticDark,
            logoLight: opticLight,
        },
        team1Score: 5,
        team2Score: 3,
        round: "Winners 1",
        date: new Date("2023-12-12T00:00:00.000+00:00"),
    },
    {
        id: 3,
        majorId: 2,
        team1: {
            id: 6,
            name: "Los Angeles Thieves",
            location: "United States",
            created: new Date("2020-11-06T05:00:00.000+00:00"),
            affiliated: "100 Thieves",
            coach: 'Jordan "JKap" Kaplan',
            owner: "N/A",
            points: 20,
            ticker: "TEST",
            logoDark: thieves,
            logoLight: thieves,
        },
        team2: {
            id: 11,
            name: "Seattle Surge",
            location: "United States",
            created: new Date("2019-09-13T04:00:00.000+00:00"),
            affiliated: "Luminosity Gaming",
            coach: 'Sam "Fenix" Spencer',
            owner: "Enthusiast Gaming  Canucks Sports & Entertainment",
            points: 30,
            ticker: "TEST",
            logoDark: surge,
            logoLight: surge,
        },
        team1Score: 5,
        team2Score: 3,
        round: "Losers 2",
        date: new Date("2023-12-12T00:00:00.000+00:00"),
    },
];

export const FUTURE_MATCHES: Match[] = [
    {
        id: 1,
        majorId: 2,
        team1: {
            id: 1,
            name: "Atlanta FaZe",
            location: "United States",
            created: new Date("2019-05-02T04:00:00.000+00:00"),
            affiliated: "FaZe Clan",
            coach: 'James "Crowder" Replays',
            owner: "Atlanta Esports Ventures",
            points: 50,
            ticker: "TEST",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team2: {
            id: 6,
            name: "Los Angeles Thieves",
            location: "United States",
            created: new Date("2020-11-06T05:00:00.000+00:00"),
            affiliated: "100 Thieves",
            coach: 'Jordan "JKap" Kaplan',
            owner: "N/A",
            points: 30,
            ticker: "TEST",
            logoDark: thieves,
            logoLight: thieves,
        },
        team1Score: 3,
        team2Score: 1,
        round: "Qualifiers",
        date: new Date("2024-04-06T00:00:00.000+00:00"),
    },
    {
        id: 1,
        majorId: 2,
        team1: {
            id: 1,
            name: "Atlanta FaZe",
            location: "United States",
            created: new Date("2019-05-02T04:00:00.000+00:00"),
            affiliated: "FaZe Clan",
            coach: 'James "Crowder" Replays',
            owner: "Atlanta Esports Ventures",
            points: 50,
            ticker: "TEST",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team2: {
            id: 6,
            name: "Los Angeles Thieves",
            location: "United States",
            created: new Date("2020-11-06T05:00:00.000+00:00"),
            affiliated: "100 Thieves",
            coach: 'Jordan "JKap" Kaplan',
            owner: "N/A",
            points: 30,
            ticker: "TEST",
            logoDark: thieves,
            logoLight: thieves,
        },
        team1Score: 3,
        team2Score: 1,
        round: "Qualifiers",
        date: new Date("2024-04-06T00:00:00.000+00:00"),
    },
    {
        id: 1,
        majorId: 2,
        team1: {
            id: 1,
            name: "Atlanta FaZe",
            location: "United States",
            created: new Date("2019-05-02T04:00:00.000+00:00"),
            affiliated: "FaZe Clan",
            coach: 'James "Crowder" Replays',
            owner: "Atlanta Esports Ventures",
            points: 50,
            ticker: "TEST",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team2: {
            id: 6,
            name: "Los Angeles",
            location: "United States",
            created: new Date("2020-11-06T05:00:00.000+00:00"),
            affiliated: "100 Thieves",
            coach: 'Jordan "JKap" Kaplan',
            owner: "N/A",
            points: 30,
            ticker: "TEST",
            logoDark: thieves,
            logoLight: thieves,
        },
        team1Score: 3,
        team2Score: 1,
        round: "Qualifiers",
        date: new Date("2024-04-06T00:00:00.000+00:00"),
    },
    {
        id: 2,
        majorId: 3,
        team1: {
            id: 4,
            name: "Las Vegas Legion",
            location: "United States",
            created: new Date("2022-09-12T04:00:00.000+00:00"),
            affiliated: "N/A",
            coach: 'Dylan "Theory" McGee',
            owner: "c0ntact Gaming, LLC",
            points: 10,
            ticker: "TEST",
            logoDark: legion,
            logoLight: legion,
        },
        team2: {
            id: 1,
            name: "OpTic Texas",
            location: "United States",
            created: new Date("2021-11-08T05:00:00.000+00:00"),
            affiliated: "Team Envy",
            coach: 'Raymond "Rambo" Lussier',
            owner: "Hector Rodriguez & Mike Rufail",
            points: 60,
            ticker: "TEST",
            logoDark: opticDark,
            logoLight: opticLight,
        },
        team1Score: 0,
        team2Score: 0,
        round: "Winners 1",
        date: new Date("2024-04-12T00:00:00.000+00:00"),
    },
    {
        id: 3,
        majorId: 3,
        team1: {
            id: 6,
            name: "Los Angeles Thieves",
            location: "United States",
            created: new Date("2020-11-06T05:00:00.000+00:00"),
            affiliated: "100 Thieves",
            coach: 'Jordan "JKap" Kaplan',
            owner: "N/A",
            points: 20,
            ticker: "TEST",
            logoDark: thieves,
            logoLight: thieves,
        },
        team2: {
            id: 11,
            name: "Seattle Surge",
            location: "United States",
            created: new Date("2019-09-13T04:00:00.000+00:00"),
            affiliated: "Luminosity Gaming",
            coach: 'Sam "Fenix" Spencer',
            owner: "Enthusiast Gaming  Canucks Sports & Entertainment",
            points: 30,
            ticker: "TEST",
            logoDark: surge,
            logoLight: surge,
        },
        team1Score: 5,
        team2Score: 3,
        round: "Losers 2",
        date: new Date("2023-05-12T00:00:00.000+00:00"),
    },
];
