import { Match } from "../types/Match";
import fazeLight from "@/assets/logos/Atlanta_FaZe_Light.png";
import fazeDark from "@/assets/logos/Atlanta_FaZe_Dark.png";
import opticLight from "@/assets/logos/OpTic_Texas_Light.png";
import opticDark from "@/assets/logos/OpTic_Texas_Dark.png";

export const MATCH_DATA: Match[] = [
    {
        id: 1,
        majorId: 1,
        team1: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoLight: opticLight,
            logoDark: opticDark,
        },
        team2: {
            id: 1,
            name: "OpTic",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team1Score: 3,
        team2Score: 2,
        round: "QUALIFIERS",
        date: new Date("2021-11-23"),
    },
    {
        id: 1,
        majorId: 1,
        team1: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoLight: opticLight,
            logoDark: opticDark,
        },
        team2: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team1Score: 2,
        team2Score: 3,
        round: "QUALIFIERS",
        date: new Date("2021-11-23"),
    },
    {
        id: 1,
        majorId: 1,
        team1: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoLight: opticLight,
            logoDark: opticDark,
        },
        team2: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team1Score: 3,
        team2Score: 0,
        round: "QUALIFIERS",
        date: new Date("2021-11-23"),
    },
    {
        id: 1,
        majorId: 1,
        team1: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoLight: opticLight,
            logoDark: opticDark,
        },
        team2: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team1Score: 1,
        team2Score: 3,
        round: "QUALIFIERS",
        date: new Date("2021-11-23"),
    },
    {
        id: 1,
        majorId: 1,
        team1: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoLight: opticLight,
            logoDark: opticDark,
        },
        team2: {
            id: 1,
            name: "OpTic Texas",
            location: "Texas",
            created: new Date("2021-11-23"),
            affiliated: "Envy",
            coach: "Karma",
            owner: "Hector Rodrigez",
            points: 50,
            bgColoured: "",
            bgDark: "",
            bgLight: "",
            logoDark: fazeDark,
            logoLight: fazeLight,
        },
        team1Score: 3,
        team2Score: 2,
        round: "QUALIFIERS",
        date: new Date("2021-11-23"),
    },
];
