import { Team } from "../types/Team";
import fazeLight from "@/assets/logos/Atlanta_FaZe_Light.png";
import fazeDark from "@/assets/logos/Atlanta_FaZe_Dark.png";
import breachLight from "@/assets/logos/Boston_Breach_Light.png";
import breachDark from "@/assets/logos/Boston_Breach_Dark.png";
import thieves from "@/assets/logos/LA-Thieves.png";
import lagLight from "@/assets/logos/LA_Guerillas_Light.png";
import lagDark from "@/assets/logos/LA_Guerillas_Dark.png";
import heretics from "@/assets/logos/Miami_Heretics.png";
import rokkr from "@/assets/logos/Minnesota_ROKKR.png";
import nysl from "@/assets/logos/NYSL.png";
import opticLight from "@/assets/logos/OpTic_Texas_Light.png";
import opticDark from "@/assets/logos/OpTic_Texas_Dark.png";
import surge from "@/assets/logos/Seattle_Surge.png";

export const TEAM_DATA: Team[] = [
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoLight: opticLight,
        logoDark: opticDark,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: fazeDark,
        logoLight: fazeLight,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: surge,
        logoLight: surge,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: thieves,
        logoLight: thieves,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: rokkr,
        logoLight: rokkr,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: breachDark,
        logoLight: breachLight,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: nysl,
        logoLight: nysl,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: heretics,
        logoLight: heretics,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logoDark: lagDark,
        logoLight: lagLight,
    },
];
