import { Team } from "../types/Team";
import logo from "@/assets/logos/OpTic_Texas_Light.png";

export const TEAM_DATA: Team[] = [
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
];
