import { Team } from "../types/Team";
import logo from "@/assets/logos/OpTic_Texas_Light.png";
import faze from "@/assets/logos/Atlanta_FaZe_Light.png";
import surge from "@/assets/logos/Seattle_Surge.png";
import thieves from "@/assets/logos/LA-Thieves.png";
import rokkr from "@/assets/logos/Minnesota_ROKKR.png";

export const TEAM_DATA: Team[] = [
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: faze,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: surge,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: thieves,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: rokkr,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
    {
        id: 1,
        name: "OpTic Texas",
        location: "Texas",
        created: new Date("2021-11-23"),
        affiliated: "Envy",
        coach: "Karma",
        owner: "Hector Rodrigez",
        points: 50,
        bgColoured: "",
        bgDark: "",
        bgLight: "",
        logo: logo,
    },
];
