package com.jpreet.cdlwiki.enums;

public enum RoundName {
    QUALIFIERS, WINNERS_1, ELIMINATION_1, WINNERS_2, ELIMINATION_2, ELIMINATION_3, ELIMINATION_4, WINNERS_FINAL, ELIMINATION_FINAL, GRAND_FINAL
}
